apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: pod-cronjob-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-cronjob-role
subjects:
- kind: ServiceAccount
  name: rbac-user
  namespace: default
