apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flask
  name: flask-svc
  namespace: p-fayoz
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: flask
  type: NodePort
status:
  loadBalancer: {}
