apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-pod-1
  name: redis-pod-1
  namespace: p-fayoz
spec:
  nodeSelector:
    redis: "true"
  containers:
  - image: redis
    name: redis-pod-1
    ports:
    - containerPort: 6379
    readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
