apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-application-2
  namespace: p-fayoz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: nvrbckdown/flask-app:p-v4
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          env:
            - name: CPU
              valueFrom:
                resourceFieldRef:
                  containerName: flask-container
                  resource: requests.cpu
            - name: MEMORY
              valueFrom:
                resourceFieldRef:
                  containerName: flask-container
                  resource: requests.memory
          livenessProbe:
            httpGet:
              path: /domain
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
